version=0.1
[default.build.parameters]
mount_with="READ"
template_file="template.yaml"

[default.local_invoke.parameters]
log_file="local_invoke.log"

[default.local_start_api.parameters]
warm_containers = "EAGER"
log_file="local_api.log"
[default.deploy.parameters]
stack_name = "pet-bot-ai"
resolve_s3 = true
s3_prefix = "pet-bot-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PetBotAppName=\"pet-bot-ai\" ApplicationEnv=\"dev\""
image_repositories = []
