AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pet Bot AI Processing Lambda

Parameters:
  PetBotAppName:
    Type: String
    Default: "pet-bot-ai"
  ApplicationEnv:
    Type: String
    Default: "dev"


Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging
      Auth:
        ApiKeyRequired: true # sets for all methods

  ApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn: [ApiUsagePlan]
    Properties: 
      Name: !Sub ${PetBotAppName}-api-key
      Description: "CloudFormation API Key V1"
      Enabled: true
      GenerateDistinctId: false
      Value: abcdefg123456665ffghsdghfgdhfgdh4565
      StageKeys:
        - RestApiId: !Ref BasicAWSApiGateway
          StageName: Staging

  ApiUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    DependsOn:
      - ServerlessHttpApiProdStage
    Properties:
      ApiStages: 
        - ApiId: !Ref BasicAWSApiGateway
          Stage: Staging
      Description: !Sub "${PetBotAppName} usage plan"
      Quota:
        Limit: 1000
        Period: MONTH
      UsagePlanName: !Sub ${PetBotAppName}-usage-plan

  ApiUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    DependsOn: 
      - ServerlessHttpApi
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
  # Define the processing Lambda function
  PetBotFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub ${PetBotAppName}-lambda
      Handler: src.lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: pet-bot-ai
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
          POWERTOOLS_LOGGER_LOG_EVENT: true
          APPLICATION_ENV: !Ref ApplicationEnv
      Policies:
        AWSSecretsManagerGetSecretValuePolicy:
          SecretArn: "arn:aws:secretsmanager:us-east-1:165443708813:secret:petbotkeys-1ipW27" #gitleaks:allow

      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: Any
            RestApiId:
              Ref: BasicAWSApiGateway
            Auth:
              ApiKeyRequired: true
Outputs:
  PetBotFunction:
    Description: PetBotFunction function name
    Value: !Ref PetBotFunction
