AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pet Bot AI Processing Lambda

Parameters:
  PetBotAppName:
    Type: String
    Default: "pet-bot-ai"


Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging

  SmsPetBotSns:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${PetBotAppName}-topic
  # Define the processing Lambda function
  PetBotFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub ${PetBotAppName}-lambda
      Handler: src.lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: pet-bot-ai
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
          POWERTOOLS_LOGGER_LOG_EVENT: true
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: Any
            RestApiId:
              Ref: BasicAWSApiGateway
Outputs:
  PetBotFunction:
    Description: PetBotFunction function name
    Value: !Ref PetBotFunction
