AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pet Bot AI Processing Lambda

Parameters:
  PetBotAppName:
    Type: String
    Default: "pet-bot-ai"
  ApplicationEnv:
    Type: String
    Default: "dev"


Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Basic AWS Api Gateway
      StageName: Staging
      Auth:
        ApiKeyRequired: true # sets for all 
  # Define the processing Lambda function
  PetBotFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub ${PetBotAppName}-lambda
      Handler: src.lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: pet-bot-ai
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
          POWERTOOLS_LOGGER_LOG_EVENT: true
          APPLICATION_ENV: !Ref ApplicationEnv
      Policies:
        AWSSecretsManagerGetSecretValuePolicy:
          SecretArn: "arn:aws:secretsmanager:us-east-1:165443708813:secret:petbotkeys-1ipW27" #gitleaks:allow

      Events:
        TelegramWebhookEvent:
          Type: Api
          Properties:
            Path: /telegram
            Method: post
            RestApiId:
              Ref: BasicAWSApiGateway
            Auth:
              ApiKeyRequired: true
        HealthEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId:
              Ref: BasicAWSApiGateway
            Auth:
              ApiKeyRequired: true
